DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
    AUTHOR_ID int(11) NOT NULL,
    AUTHOR_NAME varchar(45) NOT NULL,
    DATE_OF_BIRTH varchar(45) NOT NULL,
    ADDRESS varchar(45) NOT NULL,
    PRIMARY KEY(AUTHOR_ID)
);


DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    BOOK_ID int(11) NOT NULL,
    BOOK_NAME varchar(45) NOT NULL,
    DATE_OF_PUBLICATION varchar(45) NOT NULL,
    PRIMARY KEY(BOOK_ID)
);

DROP TABLE IF EXISTS AUTHOR_BOOK;

CREATE TABLE AUTHOR_BOOK (
    AUTHOR_ID int(11),
    BOOK_ID int(11),
    PRIMARY KEY(AUTHOR_ID, BOOK_ID)
);
